name: Azure Bicep CI / Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bicep-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Azure CLI
        uses: azure/CLI@v1
      - name: Install bicep
        run: az bicep install
      - name: Build Bicep
        run: az bicep build --file infra/bicep/main.bicep

  python-tests:
    runs-on: ubuntu-latest
    needs: bicep-validate
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run tests
        run: |
          pytest -q

  deploy-dev:
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - bicep-validate
      - python-tests
    steps:
      - uses: actions/checkout@v4
      - name: Login with service principal
        if: ${{ secrets.AZURE_CREDENTIALS }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Azure CLI
        uses: azure/CLI@v1
      - name: Install bicep
        run: az bicep install
      - name: What-if deployment (preview)
        run: az deployment group what-if --resource-group ${{ secrets.AZURE_DEV_RG }} --template-file infra/bicep/main.bicep --parameters @infra/bicep/params/dev.parameters.json
      - name: Deploy Bicep
        run: az deployment group create --resource-group ${{ secrets.AZURE_DEV_RG }} --template-file infra/bicep/main.bicep --parameters @infra/bicep/params/dev.parameters.json
